### ISSUE TITLE
[front-end] Front-page development

### ISSUE THREAD

**Issue by fbsoares** [vostpt/Open4Business#4]
**InVision Part 1**: https://projects.invisionapp.com/d/main?origin=v7#/console/19619243/410207957/preview?scrollOffset=200

**InVision Part 2**: https://projects.invisionapp.com/d/main?origin=v7#/console/19619243/410209621/preview?scrollOffset=200

**Comment by jagoncalves14** [comment]
Olá @fbsoares, 

Os links para o InVision não estão públicos. Tendo em conta que é um projeto open-source, faz sentido que assim o sejam, não?
De qualquer forma, peço-te que me dês acesso para o e-mail jagoncalves@outlook.pt

Obrigado!

**Comment by jagoncalves14** [comment]
Hi @fbsoares,

The links for InVision are currently private. Since this project is open-source, it makes sense to make them public.
In any case, if you don't plan to do that, can you simply add me to it? My e-mail is jagoncalves@outlook.pt

Thank you!

**Comment by JorgeMiguelGomes** [comment]
> Hi @fbsoares,
> 
> The links for InVision are currently private. Since this project is open-source, it makes sense to make them public.
> In any case, if you don't plan to do that, can you simply add me to it? My e-mail is [jagoncalves@outlook.pt](mailto:jagoncalves@outlook.pt)
> 
> Thank you!

@fbsoares did you send the invite so I can close this issue?
