### ISSUE TITLE
[Database] Add fields 

### ISSUE THREAD

**Issue by JorgeMiguelGomes** [vostpt/Open4Business#46]
Add fields to "Horário" type:
- Manhã 
- Tarde
- Seguido
maintain
- Forças de Segurança e Profissionais da Saúde
- Idosos
- Público em Geral

**Comment by Cotemero** [comment]
This is a new column, not the same as Forças, Idosos and Publico Geral

**Comment by JorgeMiguelGomes** [comment]
> This is a new column, not the same as Forças, Idosos and Publico Geral

Please update sample file accordingly before closing issue
