### ISSUE TITLE
[Bug] [Single Submission] By appointment 

### ISSUE THREAD

**Issue by JorgeMiguelGomes** [vostpt/Open4Business#71]
![Screenshot 2020-04-02 at 22 35 54](https://user-images.githubusercontent.com/34355337/78302382-93ff0600-7532-11ea-9261-c71cecf3f7a0.png)

Apparently the system demands that "By Marcação" is a mandatory field. It's not. 

Also, **all error messages should be in Portuguese**. Please make list to translate.

**Comment by Cotemero** [comment]
Bug fixed.
Error messages should be placed on another issue
