### ISSUE TITLE
[Workflow] Credentials 

### ISSUE THREAD

**Issue by JorgeMiguelGomes** [vostpt/Open4Business#72]
When user asks for credentials:

- [x] Gets E-mail
- [x] Clicks on Validation Link 
- [x] Fills in password 
- [x] Repeats Password
- [x] System Checks if passwords match
- [x] Clicks Login 
- [x] Goes to Mass Submission Form

**Comment by Cotemero** [comment]
Fill in password and repeats password on the same page?

**Comment by JorgeMiguelGomes** [comment]
> Fill in password and repeats password on the same page?

**Like in any service where you are asked to insert a new password, we should have the user repeat the password so that we are sure they got it right.**
