### ISSUE TITLE
[Bug] Validation E-mail 

### ISSUE THREAD

**Issue by JorgeMiguelGomes** [vostpt/Open4Business#73]
![Screenshot 2020-04-02 at 23 39 51](https://user-images.githubusercontent.com/34355337/78306473-5a7ec880-753b-11ea-8a6b-18737a57af23.png)

Top image is broken. 
Footer should say 
 **"Open 4 Business" by VOST Portugal CC - BY - SA**

**Comment by Cotemero** [comment]
Done
